apiVersion: v1
kind: Secret
metadata:
  name: {{ include "security-scanner.fullname" . }}-db
  labels:
    {{- include "security-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.db.url | quote }}
  username: {{ .Values.db.username | quote }}
  password: {{ .Values.db.password | quote }}