spring.application.name=security

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/testdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always